language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - '6'
  - '8'
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
    - .tmp
before_install:
  - git fetch origin --tags
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  # Report coverage to coveralls.io
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
  - yarn run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
